### ISSUE TITLE
Precompilation of Assets Failure:

### ISSUE THREAD

**Issue by jchapin** [capitaltechnologyservices/prelaunchr_for_ni#11]
```
remote:        Sprockets::Helpers::RailsHelper::AssetPaths::AssetNotPrecompiledError: refer/book_img.jpg isn't precompiled
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/sprockets/helpers/rails_helper.rb:142:in `digest_for'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/sprockets/helpers/rails_helper.rb:151:in `rewrite_asset_path'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/action_view/asset_paths.rb:27:in `compute_public_path'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/sprockets/helpers/rails_helper.rb:56:in `asset_path'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/app/models/user.rb:18:in `<class:User>'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/app/models/user.rb:1:in `<top (required)>'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:359:in `require_or_load'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:502:in `load_missing_constant'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:192:in `block in const_missing'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:190:in `each'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:190:in `const_missing'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/app/admin/users.rb:2:in `<top (required)>'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `load'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `block in load'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `load'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activeadmin-0.6.6/lib/active_admin/application.rb:167:in `block in load!'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activeadmin-0.6.6/lib/active_admin/application.rb:167:in `each'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activeadmin-0.6.6/lib/active_admin/application.rb:167:in `load!'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activeadmin-0.6.6/lib/active_admin/application.rb:185:in `routes'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activeadmin-0.6.6/lib/active_admin.rb:74:in `routes'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/config/routes.rb:3:in `block in <top (required)>'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:282:in `instance_exec'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:282:in `eval_block'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:260:in `draw'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/config/routes.rb:1:in `<top (required)>'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `load'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `block in load'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `load'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/application/routes_reloader.rb:40:in `each'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/application/routes_reloader.rb:40:in `load_paths'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/application/routes_reloader.rb:16:in `reload!'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/application.rb:108:in `reload_routes!'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activeadmin-0.6.6/lib/active_admin/reloader.rb:34:in `reload!'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activeadmin-0.6.6/lib/active_admin/reloader.rb:61:in `block in attach!'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:429:in `_run__22185311740834751__prepare__2859121950054392092__callbacks'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `each'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/application.rb:136:in `initialize!'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `method_missing'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/application.rb:103:in `require_environment!'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/railties-3.2.11/lib/rails/application.rb:297:in `block (2 levels) in initialize_tasks'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/sprockets/assets.rake:93:in `block (2 levels) in <top (required)>'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/sprockets/assets.rake:23:in `invoke_or_reboot_rake_task'
remote:        /tmp/build_1ea98ca873d92fcc283b6f2592de4da3/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.11/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to ni-prelauncer-dev.
remote: 
To https://git.heroku.com/ni-prelauncer-dev.git
 ! [remote rejected] check-in-changes-to-gems -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/ni-prelauncer-dev.git'
```

**Comment by jchapin** [comment]
This is all fixed.
