### ISSUE TITLE
Exception on create, unknown attribute, first_name

### ISSUE THREAD

**Issue by jchapin** [capitaltechnologyservices/prelaunchr_for_ni#18]
```
2016-02-19T20:56:36.229662+00:00 app[web.1]: Started POST "/users" for 216.127.112.163 at 2016-02-19 20:56:36 +0000
2016-02-19T20:56:36.274506+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"VA9JTDfk1fceKSLmB3pSMsTweCTtmRkYANevrvCQgkc=", "user"=>{"first_name"=>"John", "last_name"=>"Chapin", "email"=>"john@johnchapin.net", "receipt"=>#<ActionDispatch::Http::UploadedFile:0x007f5b4c162e30 @original_filename="ivocate-logo.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"user[receipt]\"; filename=\"ivocate-logo.png\"\r\nContent-Type: image/png\r\n", @tempfile=#<Tempfile:/tmp/RackMultipart20160219-12-3zse2o>>}, "commit"=>"Sign Up Now"}
2016-02-19T20:56:36.376740+00:00 app[web.1]: 
2016-02-19T20:56:36.376744+00:00 app[web.1]:   app/controllers/users_controller.rb:34:in `create'
2016-02-19T20:56:36.376743+00:00 app[web.1]: ActiveRecord::UnknownAttributeError (unknown attribute: first_name):
2016-02-19T20:56:36.376745+00:00 app[web.1]: 
2016-02-19T20:56:36.376745+00:00 app[web.1]: 
2016-02-19T20:56:36.273059+00:00 app[web.1]: Processing by UsersController#create as HTML
2016-02-19T20:56:36.374394+00:00 app[web.1]: Completed 500 Internal Server Error in 100ms
```

**Comment by jchapin** [comment]
Posting to: https://ni-prelauncer-dev.herokuapp.com/users

**Comment by jchapin** [comment]
Line 34: @user = User.create(params[:user])

```
{"first_name"=>"John"
```

The controller may not be accepting the additional form parameters.

**Comment by jchapin** [comment]
Strange, those are indeed on the table:

```
  create_table "users", :force => true do |t|
    t.string   "email"
    t.string   "referral_code"
    t.integer  "referrer_id"
    t.datetime "created_at",           :null => false
    t.datetime "updated_at",           :null => false
    t.string   "first_name"
    t.string   "last_name"
    t.string   "receipt_file_name"
    t.string   "receipt_content_type"
    t.integer  "receipt_file_size"
    t.datetime "receipt_updated_at"
  end

```

**Comment by jchapin** [comment]
```ruby
#<User id: nil, email: nil, referral_code: nil, referrer_id: nil, created_at: nil, updated_at: nil, first_name: nil, last_name: nil, receipt_file_name: nil, receipt_content_type: nil, receipt_file_size: nil, receipt_updated_at: nil>```

**Comment by jchapin** [comment]
```
2016-02-19T21:23:19.179747+00:00 app[web.1]: Processing by UsersController#create as HTML
2016-02-19T21:23:19.179821+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"uLmDkDjW1YrqqpSnhypHVXs//na8KvVdHnfPbM0nRk8=", "user"=>{"first_name"=>"John", "last_name"=>"Chapin", "email"=>"john@johnchapin.net", "receipt"=>#<ActionDispatch::Http::UploadedFile:0x007f88ad8cb148 @original_filename="ivocate-logo.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"user[receipt]\"; filename=\"ivocate-logo.png\"\r\nContent-Type: image/png\r\n", @tempfile=#<Tempfile:/tmp/RackMultipart20160219-12-1hcs57m>>}, "commit"=>"Sign Up Now"}
2016-02-19T21:23:19.233266+00:00 app[web.1]: Command :: file -b --mime '/tmp/43c52b1cb012a68155be4ed86a01b77420160219-12-1c51j1d.png'
2016-02-19T21:23:19.281983+00:00 app[web.1]: Command :: identify -format %m '/tmp/43c52b1cb012a68155be4ed86a01b77420160219-12-1rta1pw.png[0]'
2016-02-19T21:23:19.421593+00:00 app[web.1]: Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/43c52b1cb012a68155be4ed86a01b77420160219-12-1rta1pw.png[0]' 2>/dev/null
2016-02-19T21:23:19.551784+00:00 app[web.1]: Command :: file -b --mime '/tmp/43c52b1cb012a68155be4ed86a01b77420160219-12-1vn6711.png'
2016-02-19T21:23:19.446327+00:00 app[web.1]: Command :: identify -format %m '/tmp/43c52b1cb012a68155be4ed86a01b77420160219-12-1rta1pw.png[0]'
2016-02-19T21:23:19.465628+00:00 app[web.1]: Command :: convert '/tmp/43c52b1cb012a68155be4ed86a01b77420160219-12-1rta1pw.png[0]' -auto-orient -resize "100x100>" '/tmp/99a7cc921f9af45d3135b677927d72c920160219-12-14hf5s2'
2016-02-19T21:23:22.566700+00:00 app[web.1]: [paperclip] saving /users/receipts/000/000/001/original/ivocate-logo.png
2016-02-19T21:23:22.582393+00:00 app[web.1]: 
2016-02-19T21:23:22.582396+00:00 app[web.1]: NameError (uninitialized constant Paperclip::Storage::S3::AWS):
2016-02-19T21:23:22.582398+00:00 app[web.1]:   app/controllers/users_controller.rb:34:in `create'
2016-02-19T21:23:22.582398+00:00 app[web.1]: 
2016-02-19T21:23:22.582399+00:00 app[web.1]: 
2016-02-19T21:23:22.579500+00:00 app[web.1]: Completed 500 Internal Server Error in 3399ms
2016-02-19T21:23:12.359396+00:00 heroku[router]: at=info method=GET path="/assets/loading.gif" host=ni-prelaunchr-dev.herokuapp.com request_id=fca89e48-2bb5-4397-a0b4-e2487360d768 fwd="216.127.112.163" dyno=web.1 connect=1ms service=2ms status=200 bytes=6456
```

Close, but not connected yet.

**Comment by jchapin** [comment]
```
2016-02-22T19:34:31.455932+00:00 app[web.1]: Started POST "/users" for 216.127.112.163 at 2016-02-22 19:34:31 +0000
2016-02-22T19:34:31.573269+00:00 app[web.1]: Processing by UsersController#create as HTML
2016-02-22T19:34:31.573416+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"7odl/E+Z0P+S/ACpau1Xc8xkYNsp8GOP4FG62liqg1U=", "user"=>{"first_name"=>"John", "last_name"=>"Chapin", "email"=>"john@johnchapin.net", "receipt"=>#<ActionDispatch::Http::UploadedFile:0x007f5c933a5c18 @original_filename="ivocate-logo.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"user[receipt]\"; filename=\"ivocate-logo.png\"\r\nContent-Type: image/png\r\n", @tempfile=#<Tempfile:/tmp/RackMultipart20160222-11-1qctw79>>}, "commit"=>"Sign Up Now"}
2016-02-22T19:34:31.895323+00:00 app[web.1]: Command :: file -b --mime '/tmp/43c52b1cb012a68155be4ed86a01b77420160222-11-i22s0d.png'
2016-02-22T19:34:31.960556+00:00 app[web.1]: Command :: identify -format %m '/tmp/43c52b1cb012a68155be4ed86a01b77420160222-11-njwq70.png[0]'
2016-02-22T19:34:31.917449+00:00 app[web.1]: Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/43c52b1cb012a68155be4ed86a01b77420160222-11-njwq70.png[0]' 2>/dev/null
2016-02-22T19:34:31.997420+00:00 app[web.1]: Command :: convert '/tmp/43c52b1cb012a68155be4ed86a01b77420160222-11-njwq70.png[0]' -auto-orient -resize "300x300>" '/tmp/019bb900d4a739dc6ac4f06632f60fc120160222-11-1ei209v'
2016-02-22T19:34:32.256595+00:00 app[web.1]: Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/43c52b1cb012a68155be4ed86a01b77420160222-11-njwq70.png[0]' 2>/dev/null
2016-02-22T19:34:32.397178+00:00 app[web.1]: Command :: convert '/tmp/43c52b1cb012a68155be4ed86a01b77420160222-11-njwq70.png[0]' -auto-orient -resize "100x100>" '/tmp/019bb900d4a739dc6ac4f06632f60fc120160222-11-1io00zq'
2016-02-22T19:34:32.348409+00:00 app[web.1]: Command :: identify -format %m '/tmp/43c52b1cb012a68155be4ed86a01b77420160222-11-njwq70.png[0]'
2016-02-22T19:34:32.605775+00:00 app[web.1]: Command :: file -b --mime '/tmp/43c52b1cb012a68155be4ed86a01b77420160222-11-15bunoc.png'
2016-02-22T19:34:32.936041+00:00 app[web.1]: Completed 500 Internal Server Error in 1362ms
2016-02-22T19:34:32.938142+00:00 app[web.1]: 
2016-02-22T19:34:32.938145+00:00 app[web.1]: NoMethodError (undefined method `to_datetime' for false:FalseClass):
2016-02-22T19:34:32.938146+00:00 app[web.1]:   app/models/user.rb:56:in `send_welcome_email'
2016-02-22T19:34:32.938146+00:00 app[web.1]:   app/controllers/users_controller.rb:34:in `create'
```

**Comment by jchapin** [comment]
Line 34 in the controller

```
      @user = User.create(params[:user])
```

Line 56 in the model:

```
    UserMailer.delay.signup_email(self)
```

**Comment by jchapin** [comment]
Added SendGrid mail configuration to see if that's the blocker.

**Comment by jchapin** [comment]
```
Redirected to https://ni-prelaunchr-dev.herokuapp.com/
```

We'll see if the user has been created.

**Comment by jchapin** [comment]
Nope.

**Comment by jchapin** [comment]
```
(byebug) @user = User.create(params[:user])
Command :: file -b --mime '/var/folders/97/4s8cznr94qjd6tydgmzy62qc0000gn/T/43c52b1cb012a68155be4ed86a01b77420160222-66174-xaqozi.png'
Command :: identify -format '%wx%h,%[exif:orientation]' '/var/folders/97/4s8cznr94qjd6tydgmzy62qc0000gn/T/43c52b1cb012a68155be4ed86a01b77420160222-66174-y1dp8g.png[0]' 2>/dev/null
Command :: identify -format %m '/var/folders/97/4s8cznr94qjd6tydgmzy62qc0000gn/T/43c52b1cb012a68155be4ed86a01b77420160222-66174-y1dp8g.png[0]'
Command :: convert '/var/folders/97/4s8cznr94qjd6tydgmzy62qc0000gn/T/43c52b1cb012a68155be4ed86a01b77420160222-66174-y1dp8g.png[0]' -auto-orient -resize "300x300>" '/var/folders/97/4s8cznr94qjd6tydgmzy62qc0000gn/T/08b36ab4ab0f3b5f955b310a7872bcfc20160222-66174-emgdpi'
Command :: identify -format '%wx%h,%[exif:orientation]' '/var/folders/97/4s8cznr94qjd6tydgmzy62qc0000gn/T/43c52b1cb012a68155be4ed86a01b77420160222-66174-y1dp8g.png[0]' 2>/dev/null
Command :: identify -format %m '/var/folders/97/4s8cznr94qjd6tydgmzy62qc0000gn/T/43c52b1cb012a68155be4ed86a01b77420160222-66174-y1dp8g.png[0]'
Command :: convert '/var/folders/97/4s8cznr94qjd6tydgmzy62qc0000gn/T/43c52b1cb012a68155be4ed86a01b77420160222-66174-y1dp8g.png[0]' -auto-orient -resize "100x100>" '/var/folders/97/4s8cznr94qjd6tydgmzy62qc0000gn/T/08b36ab4ab0f3b5f955b310a7872bcfc20160222-66174-d0nveq'
Command :: file -b --mime '/var/folders/97/4s8cznr94qjd6tydgmzy62qc0000gn/T/43c52b1cb012a68155be4ed86a01b77420160222-66174-159zi5.png'
  Rendered user_mailer/signup_email.html.erb (8.9ms)
*** ActionView::Template::Error Exception: undefined method `encoding' for {:host=>"www.milligram.biz"}:Hash
Did you mean?  encode_json
```

**Comment by jchapin** [comment]
This is where it's getting tripped up:

```ruby
<%= Rails.application.config.action_mailer.default_url_options %>/assets/refer.jpg
```

**Comment by jchapin** [comment]
Got it. All of the previous message in the template is causing an error. To save time we should just rebuild that message from scratch.

**Comment by jchapin** [comment]
Okay, and their IP address filter was blocking me from getting to this message:

```
2016-02-22T21:23:52.388245+00:00 app[web.1]: 
2016-02-22T21:23:52.388248+00:00 app[web.1]: Sent mail to john@johnchapin.net (116ms)
2016-02-22T21:23:52.388959+00:00 app[web.1]: [paperclip] saving /users/receipts/000/000/004/original/ivocate-logo.png
2016-02-22T21:23:52.399415+00:00 app[web.1]: 
2016-02-22T21:23:52.399435+00:00 app[web.1]: NameError (uninitialized constant Paperclip::Storage::S3::AWS):
2016-02-22T21:23:52.399436+00:00 app[web.1]:   app/controllers/users_controller.rb:34:in `create'
```

**Comment by jchapin** [comment]
Working.

<img width="1392" alt="screen shot 2016-02-22 at 4 27 40 pm" src="https://cloud.githubusercontent.com/assets/116142/13233328/40662682-d981-11e5-8d80-69c27db0f46b.png">

<img width="1392" alt="screen shot 2016-02-22 at 4 27 33 pm" src="https://cloud.githubusercontent.com/assets/116142/13233329/406a8484-d981-11e5-9eff-396048453212.png">

![screen shot 2016-02-22 at 4 27 49 pm](https://cloud.githubusercontent.com/assets/116142/13233330/406b0fda-d981-11e5-950a-dcc9c80f4367.png)

**Comment by jchapin** [comment]
<img width="840" alt="screen shot 2016-02-22 at 4 28 36 pm" src="https://cloud.githubusercontent.com/assets/116142/13233355/5ae0864c-d981-11e5-9074-3cef8f503190.png">
