### ISSUE TITLE
App is throwing an exception on creation of a new user:

### ISSUE THREAD

**Issue by jchapin** [capitaltechnologyservices/prelaunchr_for_ni#31]
```
2016-02-25T20:06:40.805595+00:00 app[web.1]:   Rendered user_mailer/signup_email.html.erb (5.1ms)
2016-02-25T20:06:40.808610+00:00 app[web.1]: 
2016-02-25T20:06:40.808612+00:00 app[web.1]: ActionView::Template::Error (fb.png isn't precompiled):
2016-02-25T20:06:40.808613+00:00 app[web.1]:     623:                                                         <% twitter_message = "Check out The Mindfulness Edge book!" %>
2016-02-25T20:06:40.808614+00:00 app[web.1]:     624:   
2016-02-25T20:06:40.808615+00:00 app[web.1]:     625:                                                         <div class="social-links">
2016-02-25T20:06:40.808617+00:00 app[web.1]:     626:                                                           <a href="http://www.facebook.com/sharer/sharer.php?u=<%= CGI::escape(root_url) %>?ref=<%= CGI::escape(@user.referral_code) %>&title=The Mindfulness Edge" class="fb" target="_blank"><%= image_tag("fb.png", class: 'fb_img') %></a>
2016-02-25T20:06:40.808618+00:00 app[web.1]:     627:                                                           <div class="sep"></div>
2016-02-25T20:06:40.808619+00:00 app[web.1]:     628:                                                           <a href="http://twitter.com/share?url=<%= CGI::escape(root_url) %>?ref=<%= CGI::escape(@user.referral_code) %>&text=<%= CGI::escape(twitter_message) %>" class="twit" target="_blank"><%= image_tag("twit.png", class: 'tweet_img') %></a>
2016-02-25T20:06:40.808620+00:00 app[web.1]:     629:                                                         </div>
2016-02-25T20:06:40.808621+00:00 app[web.1]:   app/views/user_mailer/signup_email.html.erb:626:in `_app_views_user_mailer_signup_email_html_erb__1889170839201358767_70356104563160'
2016-02-25T20:06:40.808621+00:00 app[web.1]:   app/mailers/user_mailer.rb:7:in `signup_email'
2016-02-25T20:06:40.808624+00:00 app[web.1]: 
2016-02-25T20:06:40.808622+00:00 app[web.1]:   app/models/user.rb:58:in `send_welcome_email'
2016-02-25T20:06:40.808623+00:00 app[web.1]:   app/controllers/users_controller.rb:34:in `create'
2016-02-25T20:06:40.808624+00:00 app[web.1]: 
2016-02-25T20:06:40.806926+00:00 app[web.1]: Completed 500 Internal Server Error in 1141ms
peaty:prelaunchr_for_ni jchapin$ 

```

**Comment by jchapin** [comment]
ActionView::Template::Error (fb.png isn't precompiled):

**Comment by cbradshaw** [comment]
if this is due to the email template, we can omit the fb/twitter images and book image for that matter.

**Comment by jchapin** [comment]
Submission successful.

<img width="1392" alt="screen shot 2016-02-25 at 5 32 17 pm" src="https://cloud.githubusercontent.com/assets/116142/13336753/c527b654-dbe5-11e5-9c56-26b87c5a3fed.png">

**Comment by jchapin** [comment]
E-mail images aren't showing up at the moment... But let me see if that's just a mailer hostname issue that would be a non-issue in production:

![screen shot 2016-02-25 at 5 33 12 pm](https://cloud.githubusercontent.com/assets/116142/13336801/094b796a-dbe6-11e5-9fe3-d9be567f8c6c.png)

**Comment by jchapin** [comment]
It's not putting in a hostname, we can fix that too.

<img width="827" alt="screen shot 2016-02-25 at 5 37 41 pm" src="https://cloud.githubusercontent.com/assets/116142/13336876/7fa53164-dbe6-11e5-88d9-ccd7755f83e4.png">

**Comment by jchapin** [comment]
Bingo.

![screen shot 2016-02-25 at 5 48 24 pm](https://cloud.githubusercontent.com/assets/116142/13337190/023734be-dbe8-11e5-9259-c3d1713404ac.png)

**Comment by cbradshaw** [comment]
awesome! I have some styling to apply to that email obviously. Sent to client for review with the "still working on minor bugs" disclaimer.
